#app
server:
    port: 9090

#spring
spring:
  devtools:
    restart:
      enabled: false

  #  DATABASE CONFIG
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=UTF-8
    url: jdbc:mysql://101.132.154.24:31306/test?characterEncoding=UTF-8
    username: root
    password: sNMrdHMwLQC9cNXn9DuKPDeLMUtXchlP
    #password: 112233
    continue-on-error: true


#mybatis

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.kunchi.wms.entity
  typeEnumsPackage: com.kunchi.wms.entity.enums
  global-config:
    #刷新mapper 调试神器
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: auto
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql

    refresh: true
      #自定义填充策略接口实现
      #meta-object-handler: com.kunchi.wms.xxx
      #自定义SQL注入器
      #sql-injector: com.kunchi.wms.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false


#logging
logging:
  level:
    org.springframework.web: DEBUG,CONSOLE
  config: classpath:logback-dev.xml

#查看springboot开启了哪些配置
debug: true


